# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20170705_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_0',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_1',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_2',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_3',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_4',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_5',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_6',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_7',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_8',
        ),
        migrations.RemoveField(
            model_name='viewdata',
            name='rating_9',
        ),
    ]
