# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_auto_20170707_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewdata',
            old_name='extra_2',
            new_name='images',
        ),
    ]
