# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_viewdata_init_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewdata',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='images',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='init_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='labels',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='num_images',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='num_labels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='owner',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viewdata',
            name='version',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
