# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewData',
            fields=[
                ('album_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('num_images', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('extra_1', models.TextField(blank=True, null=True)),
                ('extra_2', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
